version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/"
    dockerfile: "linux.Dockerfile"
    schedule:
      interval: "monthly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
